In [1]:
import os
import shutil

def get_directories(path):
    items = os.listdir(path)
    directories = [item for item in items if os.path.isdir(os.path.join(path, item))]
    return directories

current_directory = os.getcwd()

AllResults_path = f"{current_directory}/AllResults"
if not os.path.isdir(AllResults_path):
    os.makedirs(AllResults_path)

results_directories = get_directories(current_directory)

if "AllResults" in results_directories:
    results_directories.remove("AllResults")

for dir in results_directories:

    src = f"{current_directory}/{dir}/FinalResults"
    dst = f"{AllResults_path}/{dir}"

    if os.path.exists(src):  # cek dulu
        shutil.copytree(src, dst, dirs_exist_ok=True)
        print(f"Copied: {src}")
    else:
        print(f"Skipped (no FinalResults): {dir}")

Skipped (no FinalResults): .ipynb_checkpoints
Copied: C:\Users\Lenovo\Documents\Tugas\Data_Mining\FundamentalPrediction\1_Classification/01_SKF_companySort_NoneGroup/FinalResults
Copied: C:\Users\Lenovo\Documents\Tugas\Data_Mining\FundamentalPrediction\1_Classification/02_SKF_yearSort_NoneGroup/FinalResults
Copied: C:\Users\Lenovo\Documents\Tugas\Data_Mining\FundamentalPrediction\1_Classification/03_SGKF_companySort_companyGroup/FinalResults
Copied: C:\Users\Lenovo\Documents\Tugas\Data_Mining\FundamentalPrediction\1_Classification/04_SGKF_yearSort_companyGroup/FinalResults
Copied: C:\Users\Lenovo\Documents\Tugas\Data_Mining\FundamentalPrediction\1_Classification/05_SGKF_companySort_yearGroup/FinalResults
Copied: C:\Users\Lenovo\Documents\Tugas\Data_Mining\FundamentalPrediction\1_Classification/06_SGKF_yearSort_yearGroup/FinalResults

In [2]:
finalResults_path = f"{AllResults_path}/FinalResults"
if not os.path.isdir(finalResults_path):
    os.makedirs(finalResults_path)

# Get a list of all directory names
finalResults_directories = get_directories(AllResults_path)

if "FinalResults" in finalResults_directories:
    finalResults_directories.remove("FinalResults")

print(finalResults_directories)

['01_SKF_companySort_NoneGroup', '02_SKF_yearSort_NoneGroup', '03_SGKF_companySort_companyGroup', '04_SGKF_yearSort_companyGroup', '05_SGKF_companySort_yearGroup', '06_SGKF_yearSort_yearGroup']

In [4]:
preprocessing_methods = ["MinMax"]
target_columns = ["r_dicho", "b_dicho"]


bar_plot_path = f"{finalResults_path}/bar_plot"
if not os.path.isdir(bar_plot_path):
    os.makedirs(bar_plot_path)

KBest_rankedFeatures_path = f"{finalResults_path}/KBest_rankedFeatures"
if not os.path.isdir(KBest_rankedFeatures_path):
    os.makedirs(KBest_rankedFeatures_path)

for dir in finalResults_directories:
    tmp_filePath = f"{AllResults_path}/{dir}"
    tmp_fileName = f"bar_plot.png"
    shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{bar_plot_path}/{dir}.png")

    # tmp_filePath = f"{AllResults_path}/{dir}"
    # tmp_fileName = f"final_KBest_rankedFeatures.csv"
    # shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{KBest_rankedFeatures_path}/{dir}.csv")

    for target in target_columns:

        max_path = f"{finalResults_path}/max/{target}"
        if not os.path.isdir(max_path):
            os.makedirs(max_path)

        mean_path = f"{finalResults_path}/mean/{target}"
        if not os.path.isdir(mean_path):
            os.makedirs(mean_path)

        auc_roc_mean_path = f"{finalResults_path}/auc_roc_mean/{target}"
        if not os.path.isdir(auc_roc_mean_path):
            os.makedirs(auc_roc_mean_path)

        aupr_mean_path = f"{finalResults_path}/aupr_mean/{target}"
        if not os.path.isdir(aupr_mean_path):
            os.makedirs(aupr_mean_path)

        for pp_method in preprocessing_methods:

            tmp_filePath = f"{AllResults_path}/{dir}"
            tmp_fileName = f"{target}_max.csv"
            shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{max_path}/{dir}.csv")

            tmp_filePath = f"{AllResults_path}/{dir}"
            tmp_fileName = f"{target}_mean.csv"
            shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{mean_path}/{dir}.csv")

            tmp_filePath = f"{AllResults_path}/{dir}"
            tmp_fileName = f"{target}_{pp_method}_auc_roc_mean.png"
            shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{auc_roc_mean_path}/{dir}_{pp_method}.png")

            tmp_filePath = f"{AllResults_path}/{dir}"
            tmp_fileName = f"{target}_{pp_method}_aupr_mean.png"
            shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{aupr_mean_path}/{dir}_{pp_method}.png")

In [5]:
import pandas as pd

final_df = pd.DataFrame()

for dir in finalResults_directories:
    for target in target_columns:
        tmp_filePath = f"{AllResults_path}/{dir}"
        tmp_fileName = f"{target}_mean.csv"
        tmp_df = pd.read_csv(f"{tmp_filePath}/{tmp_fileName}")
        tmp_df.insert(0, "Target", f"{target}")
        tmp_df.insert(0, "Run_sample", f"{dir.split('_', 1)[1]}")
        final_df = pd.concat((final_df, tmp_df))

final_df = final_df.reset_index(drop=True)
final_df
# final_df.style.background_gradient(cmap="Reds", axis=False)

,Run_sample,Target,Scaling,Alg,Acc Cv,Acc Te,Sp,Se,MCC,F1,AUC-ROC,AUPR
0,SKF_companySort_NoneGroup,r_dicho,MinMax,HGB,77.49 ± 1.15,75.49 ± 1.86,84.6 ± 2.46,69.74 ± 4.08,53.23 ± 2.52,77.57 ± 2.37,84.82 ± 1.4,90.77 ± 0.77
1,SKF_companySort_NoneGroup,r_dicho,MinMax,LR,75.37 ± 0.52,72.18 ± 0.76,88.73 ± 0.98,61.74 ± 1.34,49.85 ± 1.21,73.05 ± 0.95,81.22 ± 0.99,88.05 ± 0.53
2,SKF_companySort_NoneGroup,r_dicho,MinMax,RF,76.49 ± 1.22,76.59 ± 1.95,74.25 ± 3.21,78.07 ± 4.24,51.89 ± 3.19,80.26 ± 2.22,83.45 ± 1.4,89.31 ± 0.7
3,SKF_companySort_NoneGroup,r_dicho,MinMax,SVM,76.43 ± 0.63,72.8 ± 0.81,90.3 ± 1.49,61.76 ± 1.13,51.54 ± 1.68,73.47 ± 0.88,82.38 ± 2.0,88.72 ± 1.86
4,SKF_companySort_NoneGroup,b_dicho,MinMax,HGB,58.43 ± 2.59,54.37 ± 4.36,73.37 ± 4.82,43.24 ± 9.22,16.71 ± 5.24,53.38 ± 8.67,63.63 ± 3.38,73.56 ± 3.05
5,SKF_companySort_NoneGroup,b_dicho,MinMax,LR,55.3 ± 1.22,45.79 ± 2.43,91.13 ± 3.05,19.23 ± 5.51,13.75 ± 2.69,30.28 ± 7.25,64.03 ± 2.14,74.15 ± 1.67
6,SKF_companySort_NoneGroup,b_dicho,MinMax,RF,59.83 ± 2.03,62.88 ± 3.47,42.99 ± 4.16,74.53 ± 6.94,18.67 ± 5.51,71.38 ± 4.12,62.9 ± 3.12,72.75 ± 2.33
7,SKF_companySort_NoneGroup,b_dicho,MinMax,SVM,54.62 ± 1.94,44.67 ± 3.65,93.1 ± 3.44,16.3 ± 7.61,13.31 ± 4.47,25.84 ± 10.66,61.24 ± 3.13,72.84 ± 2.86
8,SKF_yearSort_NoneGroup,r_dicho,MinMax,HGB,76.06 ± 1.72,75.49 ± 1.61,83.07 ± 2.54,70.71 ± 3.7,52.65 ± 2.14,77.84 ± 2.08,84.73 ± 1.09,90.72 ± 0.58
9,SKF_yearSort_NoneGroup,r_dicho,MinMax,LR,72.29 ± 0.64,72.49 ± 0.82,88.63 ± 0.91,62.3 ± 1.46,50.27 ± 1.24,73.45 ± 1.03,81.26 ± 0.96,88.2 ± 0.56
10,SKF_yearSort_NoneGroup,r_dicho,MinMax,RF,77.14 ± 1.83,76.69 ± 1.78,72.57 ± 3.14,79.29 ± 4.11,51.72 ± 2.84,80.58 ± 2.07,83.73 ± 1.11,89.48 ± 0.55
11,SKF_yearSort_NoneGroup,r_dicho,MinMax,SVM,73.18 ± 0.6,72.82 ± 0.66,89.7 ± 1.33,62.17 ± 0.86,51.27 ± 1.45,73.66 ± 0.67,81.95 ± 1.52,88.62 ± 1.47
12,SKF_yearSort_NoneGroup,b_dicho,MinMax,HGB,54.93 ± 4.05,55.16 ± 4.38,68.87 ± 4.78,47.12 ± 8.86,15.78 ± 5.71,56.3 ± 7.77,62.68 ± 3.68,72.44 ± 3.16
13,SKF_yearSort_NoneGroup,b_dicho,MinMax,LR,46.21 ± 2.48,45.96 ± 2.48,90.79 ± 3.28,19.69 ± 5.7,13.85 ± 2.64,30.8 ± 7.54,64.32 ± 1.99,74.28 ± 1.48
14,SKF_yearSort_NoneGroup,b_dicho,MinMax,RF,65.14 ± 2.59,64.45 ± 3.01,33.13 ± 2.73,82.81 ± 5.3,18.66 ± 5.75,74.5 ± 3.03,62.03 ± 3.41,71.87 ± 2.62
15,SKF_yearSort_NoneGroup,b_dicho,MinMax,SVM,44.2 ± 3.23,43.93 ± 3.38,92.92 ± 3.54,15.22 ± 7.25,11.8 ± 4.26,24.47 ± 10.32,60.58 ± 3.76,72.14 ± 2.85
16,SGKF_companySort_companyGroup,r_dicho,MinMax,HGB,77.26 ± 0.94,75.41 ± 1.56,83.63 ± 2.15,70.25 ± 3.41,52.69 ± 2.12,77.67 ± 1.92,84.64 ± 1.14,90.76 ± 0.62
17,SGKF_companySort_companyGroup,r_dicho,MinMax,LR,75.29 ± 0.53,72.38 ± 0.84,88.65 ± 0.92,62.12 ± 1.42,50.05 ± 1.3,73.29 ± 1.03,81.33 ± 0.94,88.3 ± 0.57
18,SGKF_companySort_companyGroup,r_dicho,MinMax,RF,76.28 ± 0.98,76.73 ± 1.79,74.08 ± 2.81,78.46 ± 4.12,52.14 ± 2.79,80.4 ± 2.09,83.85 ± 1.2,89.62 ± 0.59
19,SGKF_companySort_companyGroup,r_dicho,MinMax,SVM,76.48 ± 0.62,72.93 ± 0.81,90.54 ± 1.47,61.88 ± 1.15,51.83 ± 1.63,73.64 ± 0.88,82.46 ± 1.86,89.0 ± 1.87
20,SGKF_companySort_companyGroup,b_dicho,MinMax,HGB,57.8 ± 2.3,52.11 ± 4.38,72.49 ± 6.32,40.12 ± 9.85,12.81 ± 5.1,50.01 ± 9.33,60.99 ± 3.4,71.44 ± 2.9
21,SGKF_companySort_companyGroup,b_dicho,MinMax,LR,55.21 ± 1.34,45.76 ± 2.33,90.45 ± 3.73,19.32 ± 5.54,12.99 ± 2.75,30.05 ± 7.28,63.64 ± 1.97,73.89 ± 1.64
22,SGKF_companySort_companyGroup,b_dicho,MinMax,RF,58.72 ± 1.64,61.7 ± 3.28,40.48 ± 4.83,73.82 ± 7.06,15.34 ± 5.1,70.43 ± 4.1,60.49 ± 3.03,70.79 ± 2.23
23,SGKF_companySort_companyGroup,b_dicho,MinMax,SVM,54.25 ± 1.8,43.33 ± 3.09,92.14 ± 4.55,14.6 ± 7.31,10.1 ± 3.35,23.17 ± 10.17,59.56 ± 3.1,71.56 ± 2.48
24,SGKF_yearSort_companyGroup,r_dicho,MinMax,HGB,77.2 ± 0.95,75.37 ± 1.62,83.6 ± 2.9,70.24 ± 3.86,52.68 ± 2.22,77.63 ± 2.09,84.75 ± 1.14,90.81 ± 0.66
25,SGKF_yearSort_companyGroup,r_dicho,MinMax,LR,75.29 ± 0.53,72.38 ± 0.84,88.64 ± 0.91,62.12 ± 1.42,50.05 ± 1.3,73.3 ± 1.03,81.33 ± 0.94,88.3 ± 0.57
26,SGKF_yearSort_companyGroup,r_dicho,MinMax,RF,76.37 ± 1.0,76.61 ± 1.75,73.93 ± 2.94,78.38 ± 4.08,51.91 ± 2.74,80.31 ± 2.06,83.84 ± 1.2,89.58 ± 0.61
27,SGKF_yearSort_companyGroup,r_dicho,MinMax,SVM,76.48 ± 0.62,72.93 ± 0.81,90.54 ± 1.47,61.88 ± 1.15,51.84 ± 1.64,73.64 ± 0.89,82.45 ± 1.86,89.0 ± 1.85
28,SGKF_yearSort_companyGroup,b_dicho,MinMax,HGB,58.11 ± 2.39,52.08 ± 4.45,72.6 ± 6.25,40.07 ± 10.09,12.89 ± 5.22,49.95 ± 9.54,61.02 ± 3.58,71.53 ± 3.04
29,SGKF_yearSort_companyGroup,b_dicho,MinMax,LR,55.22 ± 1.34,45.79 ± 2.32,90.45 ± 3.74,19.37 ± 5.52,13.03 ± 2.79,30.11 ± 7.28,63.64 ± 1.98,73.88 ± 1.65
30,SGKF_yearSort_companyGroup,b_dicho,MinMax,RF,58.75 ± 1.64,61.74 ± 3.25,40.2 ± 4.85,74.08 ± 6.95,15.38 ± 5.1,70.51 ± 4.01,60.58 ± 3.03,70.92 ± 2.23
31,SGKF_yearSort_companyGroup,b_dicho,MinMax,SVM,54.27 ± 1.79,43.33 ± 3.1,92.15 ± 4.54,14.6 ± 7.31,10.11 ± 3.33,23.17 ± 10.18,59.66 ± 2.96,71.61 ± 2.48
32,SGKF_companySort_yearGroup,r_dicho,MinMax,HGB,67.82 ± 1.88,64.76 ± 4.52,66.82 ± 9.01,60.85 ± 4.9,28.75 ± 7.53,62.94 ± 5.1,71.87 ± 4.28,80.44 ± 3.25
33,SGKF_companySort_yearGroup,r_dicho,MinMax,LR,67.87 ± 1.27,64.78 ± 3.14,82.1 ± 6.55,48.13 ± 5.7,31.33 ± 8.52,53.16 ± 5.44,76.5 ± 5.23,84.2 ± 5.14
34,SGKF_companySort_yearGroup,r_dicho,MinMax,RF,67.66 ± 2.21,68.08 ± 3.63,56.69 ± 9.12,71.71 ± 5.13,30.37 ± 8.92,69.62 ± 4.4,72.75 ± 5.11,81.49 ± 3.75
35,SGKF_companySort_yearGroup,r_dicho,MinMax,SVM,67.1 ± 1.61,57.96 ± 5.56,81.52 ± 5.42,36.89 ± 3.69,19.95 ± 5.5,42.87 ± 3.93,69.1 ± 2.77,79.11 ± 2.81
36,SGKF_companySort_yearGroup,b_dicho,MinMax,HGB,53.57 ± 1.52,44.84 ± 3.29,67.78 ± 8.0,36.48 ± 9.15,4.8 ± 4.06,41.12 ± 9.29,55.35 ± 2.38,66.53 ± 1.61
37,SGKF_companySort_yearGroup,b_dicho,MinMax,LR,51.86 ± 1.03,40.28 ± 1.56,82.87 ± 3.8,18.33 ± 4.08,2.15 ± 2.71,23.5 ± 5.41,57.76 ± 1.69,69.51 ± 0.8
38,SGKF_companySort_yearGroup,b_dicho,MinMax,RF,56.02 ± 1.44,57.15 ± 3.05,37.4 ± 4.65,71.94 ± 7.14,10.31 ± 4.36,67.18 ± 4.33,55.82 ± 2.1,66.61 ± 1.24
39,SGKF_companySort_yearGroup,b_dicho,MinMax,SVM,51.38 ± 0.99,38.55 ± 1.31,83.57 ± 5.49,15.02 ± 4.12,-1.78 ± 2.78,18.07 ± 5.14,54.97 ± 2.21,67.08 ± 1.54
40,SGKF_yearSort_yearGroup,r_dicho,MinMax,HGB,66.66 ± 2.65,64.63 ± 4.48,65.38 ± 7.9,61.25 ± 3.94,27.88 ± 7.71,62.96 ± 4.74,71.07 ± 4.36,79.86 ± 3.07
41,SGKF_yearSort_yearGroup,r_dicho,MinMax,LR,64.44 ± 1.12,64.86 ± 3.14,81.8 ± 6.62,48.48 ± 5.53,31.43 ± 8.39,53.45 ± 5.27,76.57 ± 5.26,84.2 ± 5.13
42,SGKF_yearSort_yearGroup,r_dicho,MinMax,RF,68.99 ± 2.97,67.44 ± 3.33,54.52 ± 9.45,73.03 ± 5.41,29.69 ± 8.88,69.95 ± 4.32,72.53 ± 5.25,81.33 ± 3.81
43,SGKF_yearSort_yearGroup,r_dicho,MinMax,SVM,63.48 ± 1.51,58.25 ± 5.7,81.12 ± 5.98,37.94 ± 4.12,20.76 ± 5.22,44.13 ± 4.06,69.52 ± 3.06,79.37 ± 2.58
44,SGKF_yearSort_yearGroup,b_dicho,MinMax,HGB,50.61 ± 3.34,46.62 ± 3.15,63.67 ± 6.92,41.1 ± 8.48,5.06 ± 3.8,46.43 ± 7.72,55.18 ± 1.8,66.28 ± 1.34
45,SGKF_yearSort_yearGroup,b_dicho,MinMax,LR,43.86 ± 1.7,40.96 ± 1.88,81.77 ± 3.39,19.98 ± 4.26,2.95 ± 2.76,26.06 ± 5.93,58.61 ± 1.92,69.97 ± 0.88
46,SGKF_yearSort_yearGroup,b_dicho,MinMax,RF,61.59 ± 2.45,58.5 ± 2.58,33.38 ± 2.94,76.41 ± 5.5,11.14 ± 4.42,69.42 ± 3.15,55.88 ± 2.21,66.75 ± 1.15
47,SGKF_yearSort_yearGroup,b_dicho,MinMax,SVM,43.52 ± 2.06,39.38 ± 1.78,81.55 ± 5.18,17.72 ± 4.71,-0.78 ± 3.04,22.13 ± 6.38,54.57 ± 2.43,66.81 ± 1.77

In [6]:
# Function to extract mean and std components and convert to numeric types
def extract_and_convert(value):
    mean, std = map(float, value.split(' ± '))
    return mean, std

metrics = [
    'Acc Cv', 'Acc Te', 'Sp', 'Se',
    'MCC', 'F1', 'AUC-ROC', 'AUPR'
]

new_final_df = pd.DataFrame()
for i, col in enumerate(final_df.columns):
    if col not in metrics:
        new_final_df[col] = final_df[col].values.copy()

    else:
        new_final_df[[f"{col}_mean", f"{col}_std"]] = final_df[col].apply(extract_and_convert).apply(pd.Series)

new_final_df

,Run_sample,Target,Scaling,Alg,Acc Cv_mean,Acc Cv_std,Acc Te_mean,Acc Te_std,Sp_mean,Sp_std,Se_mean,Se_std,MCC_mean,MCC_std,F1_mean,F1_std,AUC-ROC_mean,AUC-ROC_std,AUPR_mean,AUPR_std
0,SKF_companySort_NoneGroup,r_dicho,MinMax,HGB,77.49,1.15,75.49,1.86,84.60,2.46,69.74,4.08,53.23,2.52,77.57,2.37,84.82,1.40,90.77,0.77
1,SKF_companySort_NoneGroup,r_dicho,MinMax,LR,75.37,0.52,72.18,0.76,88.73,0.98,61.74,1.34,49.85,1.21,73.05,0.95,81.22,0.99,88.05,0.53
2,SKF_companySort_NoneGroup,r_dicho,MinMax,RF,76.49,1.22,76.59,1.95,74.25,3.21,78.07,4.24,51.89,3.19,80.26,2.22,83.45,1.40,89.31,0.70
3,SKF_companySort_NoneGroup,r_dicho,MinMax,SVM,76.43,0.63,72.80,0.81,90.30,1.49,61.76,1.13,51.54,1.68,73.47,0.88,82.38,2.00,88.72,1.86
4,SKF_companySort_NoneGroup,b_dicho,MinMax,HGB,58.43,2.59,54.37,4.36,73.37,4.82,43.24,9.22,16.71,5.24,53.38,8.67,63.63,3.38,73.56,3.05
5,SKF_companySort_NoneGroup,b_dicho,MinMax,LR,55.30,1.22,45.79,2.43,91.13,3.05,19.23,5.51,13.75,2.69,30.28,7.25,64.03,2.14,74.15,1.67
6,SKF_companySort_NoneGroup,b_dicho,MinMax,RF,59.83,2.03,62.88,3.47,42.99,4.16,74.53,6.94,18.67,5.51,71.38,4.12,62.90,3.12,72.75,2.33
7,SKF_companySort_NoneGroup,b_dicho,MinMax,SVM,54.62,1.94,44.67,3.65,93.10,3.44,16.30,7.61,13.31,4.47,25.84,10.66,61.24,3.13,72.84,2.86
8,SKF_yearSort_NoneGroup,r_dicho,MinMax,HGB,76.06,1.72,75.49,1.61,83.07,2.54,70.71,3.70,52.65,2.14,77.84,2.08,84.73,1.09,90.72,0.58
9,SKF_yearSort_NoneGroup,r_dicho,MinMax,LR,72.29,0.64,72.49,0.82,88.63,0.91,62.30,1.46,50.27,1.24,73.45,1.03,81.26,0.96,88.20,0.56
10,SKF_yearSort_NoneGroup,r_dicho,MinMax,RF,77.14,1.83,76.69,1.78,72.57,3.14,79.29,4.11,51.72,2.84,80.58,2.07,83.73,1.11,89.48,0.55
11,SKF_yearSort_NoneGroup,r_dicho,MinMax,SVM,73.18,0.60,72.82,0.66,89.70,1.33,62.17,0.86,51.27,1.45,73.66,0.67,81.95,1.52,88.62,1.47
12,SKF_yearSort_NoneGroup,b_dicho,MinMax,HGB,54.93,4.05,55.16,4.38,68.87,4.78,47.12,8.86,15.78,5.71,56.30,7.77,62.68,3.68,72.44,3.16
13,SKF_yearSort_NoneGroup,b_dicho,MinMax,LR,46.21,2.48,45.96,2.48,90.79,3.28,19.69,5.70,13.85,2.64,30.80,7.54,64.32,1.99,74.28,1.48
14,SKF_yearSort_NoneGroup,b_dicho,MinMax,RF,65.14,2.59,64.45,3.01,33.13,2.73,82.81,5.30,18.66,5.75,74.50,3.03,62.03,3.41,71.87,2.62
15,SKF_yearSort_NoneGroup,b_dicho,MinMax,SVM,44.20,3.23,43.93,3.38,92.92,3.54,15.22,7.25,11.80,4.26,24.47,10.32,60.58,3.76,72.14,2.85
16,SGKF_companySort_companyGroup,r_dicho,MinMax,HGB,77.26,0.94,75.41,1.56,83.63,2.15,70.25,3.41,52.69,2.12,77.67,1.92,84.64,1.14,90.76,0.62
17,SGKF_companySort_companyGroup,r_dicho,MinMax,LR,75.29,0.53,72.38,0.84,88.65,0.92,62.12,1.42,50.05,1.30,73.29,1.03,81.33,0.94,88.30,0.57
18,SGKF_companySort_companyGroup,r_dicho,MinMax,RF,76.28,0.98,76.73,1.79,74.08,2.81,78.46,4.12,52.14,2.79,80.40,2.09,83.85,1.20,89.62,0.59
19,SGKF_companySort_companyGroup,r_dicho,MinMax,SVM,76.48,0.62,72.93,0.81,90.54,1.47,61.88,1.15,51.83,1.63,73.64,0.88,82.46,1.86,89.00,1.87
20,SGKF_companySort_companyGroup,b_dicho,MinMax,HGB,57.80,2.30,52.11,4.38,72.49,6.32,40.12,9.85,12.81,5.10,50.01,9.33,60.99,3.40,71.44,2.90
21,SGKF_companySort_companyGroup,b_dicho,MinMax,LR,55.21,1.34,45.76,2.33,90.45,3.73,19.32,5.54,12.99,2.75,30.05,7.28,63.64,1.97,73.89,1.64
22,SGKF_companySort_companyGroup,b_dicho,MinMax,RF,58.72,1.64,61.70,3.28,40.48,4.83,73.82,7.06,15.34,5.10,70.43,4.10,60.49,3.03,70.79,2.23
23,SGKF_companySort_companyGroup,b_dicho,MinMax,SVM,54.25,1.80,43.33,3.09,92.14,4.55,14.60,7.31,10.10,3.35,23.17,10.17,59.56,3.10,71.56,2.48
24,SGKF_yearSort_companyGroup,r_dicho,MinMax,HGB,77.20,0.95,75.37,1.62,83.60,2.90,70.24,3.86,52.68,2.22,77.63,2.09,84.75,1.14,90.81,0.66
25,SGKF_yearSort_companyGroup,r_dicho,MinMax,LR,75.29,0.53,72.38,0.84,88.64,0.91,62.12,1.42,50.05,1.30,73.30,1.03,81.33,0.94,88.30,0.57
26,SGKF_yearSort_companyGroup,r_dicho,MinMax,RF,76.37,1.00,76.61,1.75,73.93,2.94,78.38,4.08,51.91,2.74,80.31,2.06,83.84,1.20,89.58,0.61
27,SGKF_yearSort_companyGroup,r_dicho,MinMax,SVM,76.48,0.62,72.93,0.81,90.54,1.47,61.88,1.15,51.84,1.64,73.64,0.89,82.45,1.86,89.00,1.85
28,SGKF_yearSort_companyGroup,b_dicho,MinMax,HGB,58.11,2.39,52.08,4.45,72.60,6.25,40.07,10.09,12.89,5.22,49.95,9.54,61.02,3.58,71.53,3.04
29,SGKF_yearSort_companyGroup,b_dicho,MinMax,LR,55.22,1.34,45.79,2.32,90.45,3.74,19.37,5.52,13.03,2.79,30.11,7.28,63.64,1.98,73.88,1.65
30,SGKF_yearSort_companyGroup,b_dicho,MinMax,RF,58.75,1.64,61.74,3.25,40.20,4.85,74.08,6.95,15.38,5.10,70.51,4.01,60.58,3.03,70.92,2.23
31,SGKF_yearSort_companyGroup,b_dicho,MinMax,SVM,54.27,1.79,43.33,3.10,92.15,4.54,14.60,7.31,10.11,3.33,23.17,10.18,59.66,2.96,71.61,2.48
32,SGKF_companySort_yearGroup,r_dicho,MinMax,HGB,67.82,1.88,64.76,4.52,66.82,9.01,60.85,4.90,28.75,7.53,62.94,5.10,71.87,4.28,80.44,3.25
33,SGKF_companySort_yearGroup,r_dicho,MinMax,LR,67.87,1.27,64.78,3.14,82.10,6.55,48.13,5.70,31.33,8.52,53.16,5.44,76.50,5.23,84.20,5.14
34,SGKF_companySort_yearGroup,r_dicho,MinMax,RF,67.66,2.21,68.08,3.63,56.69,9.12,71.71,5.13,30.37,8.92,69.62,4.40,72.75,5.11,81.49,3.75
35,SGKF_companySort_yearGroup,r_dicho,MinMax,SVM,67.10,1.61,57.96,5.56,81.52,5.42,36.89,3.69,19.95,5.50,42.87,3.93,69.10,2.77,79.11,2.81
36,SGKF_companySort_yearGroup,b_dicho,MinMax,HGB,53.57,1.52,44.84,3.29,67.78,8.00,36.48,9.15,4.80,4.06,41.12,9.29,55.35,2.38,66.53,1.61
37,SGKF_companySort_yearGroup,b_dicho,MinMax,LR,51.86,1.03,40.28,1.56,82.87,3.80,18.33,4.08,2.15,2.71,23.50,5.41,57.76,1.69,69.51,0.80
38,SGKF_companySort_yearGroup,b_dicho,MinMax,RF,56.02,1.44,57.15,3.05,37.40,4.65,71.94,7.14,10.31,4.36,67.18,4.33,55.82,2.10,66.61,1.24
39,SGKF_companySort_yearGroup,b_dicho,MinMax,SVM,51.38,0.99,38.55,1.31,83.57,5.49,15.02,4.12,-1.78,2.78,18.07,5.14,54.97,2.21,67.08,1.54
40,SGKF_yearSort_yearGroup,r_dicho,MinMax,HGB,66.66,2.65,64.63,4.48,65.38,7.90,61.25,3.94,27.88,7.71,62.96,4.74,71.07,4.36,79.86,3.07
41,SGKF_yearSort_yearGroup,r_dicho,MinMax,LR,64.44,1.12,64.86,3.14,81.80,6.62,48.48,5.53,31.43,8.39,53.45,5.27,76.57,5.26,84.20,5.13
42,SGKF_yearSort_yearGroup,r_dicho,MinMax,RF,68.99,2.97,67.44,3.33,54.52,9.45,73.03,5.41,29.69,8.88,69.95,4.32,72.53,5.25,81.33,3.81
43,SGKF_yearSort_yearGroup,r_dicho,MinMax,SVM,63.48,1.51,58.25,5.70,81.12,5.98,37.94,4.12,20.76,5.22,44.13,4.06,69.52,3.06,79.37,2.58
44,SGKF_yearSort_yearGroup,b_dicho,MinMax,HGB,50.61,3.34,46.62,3.15,63.67,6.92,41.10,8.48,5.06,3.80,46.43,7.72,55.18,1.80,66.28,1.34
45,SGKF_yearSort_yearGroup,b_dicho,MinMax,LR,43.86,1.70,40.96,1.88,81.77,3.39,19.98,4.26,2.95,2.76,26.06,5.93,58.61,1.92,69.97,0.88
46,SGKF_yearSort_yearGroup,b_dicho,MinMax,RF,61.59,2.45,58.50,2.58,33.38,2.94,76.41,5.50,11.14,4.42,69.42,3.15,55.88,2.21,66.75,1.15
47,SGKF_yearSort_yearGroup,b_dicho,MinMax,SVM,43.52,2.06,39.38,1.78,81.55,5.18,17.72,4.71,-0.78,3.04,22.13,6.38,54.57,2.43,66.81,1.77

In [7]:
new_final_df = new_final_df.sort_values(by="AUPR_mean", ascending=False, ignore_index=True)
new_final_df.to_csv("final_df.csv", index=False)
new_final_df

,Run_sample,Target,Scaling,Alg,Acc Cv_mean,Acc Cv_std,Acc Te_mean,Acc Te_std,Sp_mean,Sp_std,Se_mean,Se_std,MCC_mean,MCC_std,F1_mean,F1_std,AUC-ROC_mean,AUC-ROC_std,AUPR_mean,AUPR_std
0,SGKF_yearSort_companyGroup,r_dicho,MinMax,HGB,77.20,0.95,75.37,1.62,83.60,2.90,70.24,3.86,52.68,2.22,77.63,2.09,84.75,1.14,90.81,0.66
1,SKF_companySort_NoneGroup,r_dicho,MinMax,HGB,77.49,1.15,75.49,1.86,84.60,2.46,69.74,4.08,53.23,2.52,77.57,2.37,84.82,1.40,90.77,0.77
2,SGKF_companySort_companyGroup,r_dicho,MinMax,HGB,77.26,0.94,75.41,1.56,83.63,2.15,70.25,3.41,52.69,2.12,77.67,1.92,84.64,1.14,90.76,0.62
3,SKF_yearSort_NoneGroup,r_dicho,MinMax,HGB,76.06,1.72,75.49,1.61,83.07,2.54,70.71,3.70,52.65,2.14,77.84,2.08,84.73,1.09,90.72,0.58
4,SGKF_companySort_companyGroup,r_dicho,MinMax,RF,76.28,0.98,76.73,1.79,74.08,2.81,78.46,4.12,52.14,2.79,80.40,2.09,83.85,1.20,89.62,0.59
5,SGKF_yearSort_companyGroup,r_dicho,MinMax,RF,76.37,1.00,76.61,1.75,73.93,2.94,78.38,4.08,51.91,2.74,80.31,2.06,83.84,1.20,89.58,0.61
6,SKF_yearSort_NoneGroup,r_dicho,MinMax,RF,77.14,1.83,76.69,1.78,72.57,3.14,79.29,4.11,51.72,2.84,80.58,2.07,83.73,1.11,89.48,0.55
7,SKF_companySort_NoneGroup,r_dicho,MinMax,RF,76.49,1.22,76.59,1.95,74.25,3.21,78.07,4.24,51.89,3.19,80.26,2.22,83.45,1.40,89.31,0.70
8,SGKF_yearSort_companyGroup,r_dicho,MinMax,SVM,76.48,0.62,72.93,0.81,90.54,1.47,61.88,1.15,51.84,1.64,73.64,0.89,82.45,1.86,89.00,1.85
9,SGKF_companySort_companyGroup,r_dicho,MinMax,SVM,76.48,0.62,72.93,0.81,90.54,1.47,61.88,1.15,51.83,1.63,73.64,0.88,82.46,1.86,89.00,1.87
10,SKF_companySort_NoneGroup,r_dicho,MinMax,SVM,76.43,0.63,72.80,0.81,90.30,1.49,61.76,1.13,51.54,1.68,73.47,0.88,82.38,2.00,88.72,1.86
11,SKF_yearSort_NoneGroup,r_dicho,MinMax,SVM,73.18,0.60,72.82,0.66,89.70,1.33,62.17,0.86,51.27,1.45,73.66,0.67,81.95,1.52,88.62,1.47
12,SGKF_companySort_companyGroup,r_dicho,MinMax,LR,75.29,0.53,72.38,0.84,88.65,0.92,62.12,1.42,50.05,1.30,73.29,1.03,81.33,0.94,88.30,0.57
13,SGKF_yearSort_companyGroup,r_dicho,MinMax,LR,75.29,0.53,72.38,0.84,88.64,0.91,62.12,1.42,50.05,1.30,73.30,1.03,81.33,0.94,88.30,0.57
14,SKF_yearSort_NoneGroup,r_dicho,MinMax,LR,72.29,0.64,72.49,0.82,88.63,0.91,62.30,1.46,50.27,1.24,73.45,1.03,81.26,0.96,88.20,0.56
15,SKF_companySort_NoneGroup,r_dicho,MinMax,LR,75.37,0.52,72.18,0.76,88.73,0.98,61.74,1.34,49.85,1.21,73.05,0.95,81.22,0.99,88.05,0.53
16,SGKF_yearSort_yearGroup,r_dicho,MinMax,LR,64.44,1.12,64.86,3.14,81.80,6.62,48.48,5.53,31.43,8.39,53.45,5.27,76.57,5.26,84.20,5.13
17,SGKF_companySort_yearGroup,r_dicho,MinMax,LR,67.87,1.27,64.78,3.14,82.10,6.55,48.13,5.70,31.33,8.52,53.16,5.44,76.50,5.23,84.20,5.14
18,SGKF_companySort_yearGroup,r_dicho,MinMax,RF,67.66,2.21,68.08,3.63,56.69,9.12,71.71,5.13,30.37,8.92,69.62,4.40,72.75,5.11,81.49,3.75
19,SGKF_yearSort_yearGroup,r_dicho,MinMax,RF,68.99,2.97,67.44,3.33,54.52,9.45,73.03,5.41,29.69,8.88,69.95,4.32,72.53,5.25,81.33,3.81
20,SGKF_companySort_yearGroup,r_dicho,MinMax,HGB,67.82,1.88,64.76,4.52,66.82,9.01,60.85,4.90,28.75,7.53,62.94,5.10,71.87,4.28,80.44,3.25
21,SGKF_yearSort_yearGroup,r_dicho,MinMax,HGB,66.66,2.65,64.63,4.48,65.38,7.90,61.25,3.94,27.88,7.71,62.96,4.74,71.07,4.36,79.86,3.07
22,SGKF_yearSort_yearGroup,r_dicho,MinMax,SVM,63.48,1.51,58.25,5.70,81.12,5.98,37.94,4.12,20.76,5.22,44.13,4.06,69.52,3.06,79.37,2.58
23,SGKF_companySort_yearGroup,r_dicho,MinMax,SVM,67.10,1.61,57.96,5.56,81.52,5.42,36.89,3.69,19.95,5.50,42.87,3.93,69.10,2.77,79.11,2.81
24,SKF_yearSort_NoneGroup,b_dicho,MinMax,LR,46.21,2.48,45.96,2.48,90.79,3.28,19.69,5.70,13.85,2.64,30.80,7.54,64.32,1.99,74.28,1.48
25,SKF_companySort_NoneGroup,b_dicho,MinMax,LR,55.30,1.22,45.79,2.43,91.13,3.05,19.23,5.51,13.75,2.69,30.28,7.25,64.03,2.14,74.15,1.67
26,SGKF_companySort_companyGroup,b_dicho,MinMax,LR,55.21,1.34,45.76,2.33,90.45,3.73,19.32,5.54,12.99,2.75,30.05,7.28,63.64,1.97,73.89,1.64
27,SGKF_yearSort_companyGroup,b_dicho,MinMax,LR,55.22,1.34,45.79,2.32,90.45,3.74,19.37,5.52,13.03,2.79,30.11,7.28,63.64,1.98,73.88,1.65
28,SKF_companySort_NoneGroup,b_dicho,MinMax,HGB,58.43,2.59,54.37,4.36,73.37,4.82,43.24,9.22,16.71,5.24,53.38,8.67,63.63,3.38,73.56,3.05
29,SKF_companySort_NoneGroup,b_dicho,MinMax,SVM,54.62,1.94,44.67,3.65,93.10,3.44,16.30,7.61,13.31,4.47,25.84,10.66,61.24,3.13,72.84,2.86
30,SKF_companySort_NoneGroup,b_dicho,MinMax,RF,59.83,2.03,62.88,3.47,42.99,4.16,74.53,6.94,18.67,5.51,71.38,4.12,62.90,3.12,72.75,2.33
31,SKF_yearSort_NoneGroup,b_dicho,MinMax,HGB,54.93,4.05,55.16,4.38,68.87,4.78,47.12,8.86,15.78,5.71,56.30,7.77,62.68,3.68,72.44,3.16
32,SKF_yearSort_NoneGroup,b_dicho,MinMax,SVM,44.20,3.23,43.93,3.38,92.92,3.54,15.22,7.25,11.80,4.26,24.47,10.32,60.58,3.76,72.14,2.85
33,SKF_yearSort_NoneGroup,b_dicho,MinMax,RF,65.14,2.59,64.45,3.01,33.13,2.73,82.81,5.30,18.66,5.75,74.50,3.03,62.03,3.41,71.87,2.62
34,SGKF_yearSort_companyGroup,b_dicho,MinMax,SVM,54.27,1.79,43.33,3.10,92.15,4.54,14.60,7.31,10.11,3.33,23.17,10.18,59.66,2.96,71.61,2.48
35,SGKF_companySort_companyGroup,b_dicho,MinMax,SVM,54.25,1.80,43.33,3.09,92.14,4.55,14.60,7.31,10.10,3.35,23.17,10.17,59.56,3.10,71.56,2.48
36,SGKF_yearSort_companyGroup,b_dicho,MinMax,HGB,58.11,2.39,52.08,4.45,72.60,6.25,40.07,10.09,12.89,5.22,49.95,9.54,61.02,3.58,71.53,3.04
37,SGKF_companySort_companyGroup,b_dicho,MinMax,HGB,57.80,2.30,52.11,4.38,72.49,6.32,40.12,9.85,12.81,5.10,50.01,9.33,60.99,3.40,71.44,2.90
38,SGKF_yearSort_companyGroup,b_dicho,MinMax,RF,58.75,1.64,61.74,3.25,40.20,4.85,74.08,6.95,15.38,5.10,70.51,4.01,60.58,3.03,70.92,2.23
39,SGKF_companySort_companyGroup,b_dicho,MinMax,RF,58.72,1.64,61.70,3.28,40.48,4.83,73.82,7.06,15.34,5.10,70.43,4.10,60.49,3.03,70.79,2.23
40,SGKF_yearSort_yearGroup,b_dicho,MinMax,LR,43.86,1.70,40.96,1.88,81.77,3.39,19.98,4.26,2.95,2.76,26.06,5.93,58.61,1.92,69.97,0.88
41,SGKF_companySort_yearGroup,b_dicho,MinMax,LR,51.86,1.03,40.28,1.56,82.87,3.80,18.33,4.08,2.15,2.71,23.50,5.41,57.76,1.69,69.51,0.80
42,SGKF_companySort_yearGroup,b_dicho,MinMax,SVM,51.38,0.99,38.55,1.31,83.57,5.49,15.02,4.12,-1.78,2.78,18.07,5.14,54.97,2.21,67.08,1.54
43,SGKF_yearSort_yearGroup,b_dicho,MinMax,SVM,43.52,2.06,39.38,1.78,81.55,5.18,17.72,4.71,-0.78,3.04,22.13,6.38,54.57,2.43,66.81,1.77
44,SGKF_yearSort_yearGroup,b_dicho,MinMax,RF,61.59,2.45,58.50,2.58,33.38,2.94,76.41,5.50,11.14,4.42,69.42,3.15,55.88,2.21,66.75,1.15
45,SGKF_companySort_yearGroup,b_dicho,MinMax,RF,56.02,1.44,57.15,3.05,37.40,4.65,71.94,7.14,10.31,4.36,67.18,4.33,55.82,2.10,66.61,1.24
46,SGKF_companySort_yearGroup,b_dicho,MinMax,HGB,53.57,1.52,44.84,3.29,67.78,8.00,36.48,9.15,4.80,4.06,41.12,9.29,55.35,2.38,66.53,1.61
47,SGKF_yearSort_yearGroup,b_dicho,MinMax,HGB,50.61,3.34,46.62,3.15,63.67,6.92,41.10,8.48,5.06,3.80,46.43,7.72,55.18,1.80,66.28,1.34

In [8]:
for target in target_columns:
    tmp_df = new_final_df.groupby("Target").get_group(target).reset_index(drop=True)
    tmp_df.drop(columns="Target", inplace=True)
    tmp_df.to_csv(f"{target}_df.csv", index=False)

In [9]:
# Load the DataFrame
r_dicho_df = pd.read_csv("r_dicho_df.csv")
r_dicho_df = r_dicho_df[r_dicho_df["Alg"] != "DT"]
r_dicho_df

,Run_sample,Scaling,Alg,Acc Cv_mean,Acc Cv_std,Acc Te_mean,Acc Te_std,Sp_mean,Sp_std,Se_mean,Se_std,MCC_mean,MCC_std,F1_mean,F1_std,AUC-ROC_mean,AUC-ROC_std,AUPR_mean,AUPR_std
0,SGKF_yearSort_companyGroup,MinMax,HGB,77.20,0.95,75.37,1.62,83.60,2.90,70.24,3.86,52.68,2.22,77.63,2.09,84.75,1.14,90.81,0.66
1,SKF_companySort_NoneGroup,MinMax,HGB,77.49,1.15,75.49,1.86,84.60,2.46,69.74,4.08,53.23,2.52,77.57,2.37,84.82,1.40,90.77,0.77
2,SGKF_companySort_companyGroup,MinMax,HGB,77.26,0.94,75.41,1.56,83.63,2.15,70.25,3.41,52.69,2.12,77.67,1.92,84.64,1.14,90.76,0.62
3,SKF_yearSort_NoneGroup,MinMax,HGB,76.06,1.72,75.49,1.61,83.07,2.54,70.71,3.70,52.65,2.14,77.84,2.08,84.73,1.09,90.72,0.58
4,SGKF_companySort_companyGroup,MinMax,RF,76.28,0.98,76.73,1.79,74.08,2.81,78.46,4.12,52.14,2.79,80.40,2.09,83.85,1.20,89.62,0.59
5,SGKF_yearSort_companyGroup,MinMax,RF,76.37,1.00,76.61,1.75,73.93,2.94,78.38,4.08,51.91,2.74,80.31,2.06,83.84,1.20,89.58,0.61
6,SKF_yearSort_NoneGroup,MinMax,RF,77.14,1.83,76.69,1.78,72.57,3.14,79.29,4.11,51.72,2.84,80.58,2.07,83.73,1.11,89.48,0.55
7,SKF_companySort_NoneGroup,MinMax,RF,76.49,1.22,76.59,1.95,74.25,3.21,78.07,4.24,51.89,3.19,80.26,2.22,83.45,1.40,89.31,0.70
8,SGKF_yearSort_companyGroup,MinMax,SVM,76.48,0.62,72.93,0.81,90.54,1.47,61.88,1.15,51.84,1.64,73.64,0.89,82.45,1.86,89.00,1.85
9,SGKF_companySort_companyGroup,MinMax,SVM,76.48,0.62,72.93,0.81,90.54,1.47,61.88,1.15,51.83,1.63,73.64,0.88,82.46,1.86,89.00,1.87
10,SKF_companySort_NoneGroup,MinMax,SVM,76.43,0.63,72.80,0.81,90.30,1.49,61.76,1.13,51.54,1.68,73.47,0.88,82.38,2.00,88.72,1.86
11,SKF_yearSort_NoneGroup,MinMax,SVM,73.18,0.60,72.82,0.66,89.70,1.33,62.17,0.86,51.27,1.45,73.66,0.67,81.95,1.52,88.62,1.47
12,SGKF_companySort_companyGroup,MinMax,LR,75.29,0.53,72.38,0.84,88.65,0.92,62.12,1.42,50.05,1.30,73.29,1.03,81.33,0.94,88.30,0.57
13,SGKF_yearSort_companyGroup,MinMax,LR,75.29,0.53,72.38,0.84,88.64,0.91,62.12,1.42,50.05,1.30,73.30,1.03,81.33,0.94,88.30,0.57
14,SKF_yearSort_NoneGroup,MinMax,LR,72.29,0.64,72.49,0.82,88.63,0.91,62.30,1.46,50.27,1.24,73.45,1.03,81.26,0.96,88.20,0.56
15,SKF_companySort_NoneGroup,MinMax,LR,75.37,0.52,72.18,0.76,88.73,0.98,61.74,1.34,49.85,1.21,73.05,0.95,81.22,0.99,88.05,0.53
16,SGKF_yearSort_yearGroup,MinMax,LR,64.44,1.12,64.86,3.14,81.80,6.62,48.48,5.53,31.43,8.39,53.45,5.27,76.57,5.26,84.20,5.13
17,SGKF_companySort_yearGroup,MinMax,LR,67.87,1.27,64.78,3.14,82.10,6.55,48.13,5.70,31.33,8.52,53.16,5.44,76.50,5.23,84.20,5.14
18,SGKF_companySort_yearGroup,MinMax,RF,67.66,2.21,68.08,3.63,56.69,9.12,71.71,5.13,30.37,8.92,69.62,4.40,72.75,5.11,81.49,3.75
19,SGKF_yearSort_yearGroup,MinMax,RF,68.99,2.97,67.44,3.33,54.52,9.45,73.03,5.41,29.69,8.88,69.95,4.32,72.53,5.25,81.33,3.81
20,SGKF_companySort_yearGroup,MinMax,HGB,67.82,1.88,64.76,4.52,66.82,9.01,60.85,4.90,28.75,7.53,62.94,5.10,71.87,4.28,80.44,3.25
21,SGKF_yearSort_yearGroup,MinMax,HGB,66.66,2.65,64.63,4.48,65.38,7.90,61.25,3.94,27.88,7.71,62.96,4.74,71.07,4.36,79.86,3.07
22,SGKF_yearSort_yearGroup,MinMax,SVM,63.48,1.51,58.25,5.70,81.12,5.98,37.94,4.12,20.76,5.22,44.13,4.06,69.52,3.06,79.37,2.58
23,SGKF_companySort_yearGroup,MinMax,SVM,67.10,1.61,57.96,5.56,81.52,5.42,36.89,3.69,19.95,5.50,42.87,3.93,69.10,2.77,79.11,2.81

In [10]:
def table_generator(df_path, all=False):

    df = pd.read_csv(f"{df_path}_df.csv")

    # Rename and clean columns
    for col in df.columns:
        if "Acc Te" in col:
            df = df.rename(columns={col: col.replace("Acc Te_mean", "Acc")})
        if "_mean" in col:
            df = df.rename(columns={col: col.replace("_mean", "")})
        if "_std" in col:
            df = df.drop(columns=col)

    df = df[df["Alg"] != "DT"]  # Remove the 'DT' algorithm

    df = df[['Run_sample', 'Alg', 'Scaling', 'Acc', 'MCC', 'AUC-ROC', 'AUPR']]

    # Split 'Run_sample' into separate columns
    Run_sample = ['Fold', 'Sort', 'Group']
    df[Run_sample] = df['Run_sample'].str.split('_', expand=True)
    df = df.drop(columns=["Run_sample"])
    df['Sort'] = df['Sort'].str.replace('Sort', '')
    df['Group'] = df['Group'].str.replace('Group', '')

    df = df.sort_values(by=['AUPR', 'AUC-ROC'], ascending=[False, False], ignore_index = True)

    if all == True:
        df = df[['Alg', 'Fold', 'Group', 'Sort', 'Scaling', 'Acc', 'MCC', 'AUC-ROC', 'AUPR']]

        # Set the index
        df = df.set_index(['Alg', 'Fold', 'Group', 'Sort', 'Scaling'])

    else:

        # df = df[df['Sort'] != "company"]  # Filter out 'company' sort

        df = df[['Alg', 'Group', 'Acc', 'MCC', 'AUC-ROC', 'AUPR']]

        df = df.drop_duplicates(subset=['Alg','Group'], keep='first')

        # Calculate the maximum AUPR value for each algorithm group
        max_aupr_per_alg = df.groupby(by=['Alg'])['AUPR'].max().reset_index()
        max_aupr_per_alg = max_aupr_per_alg.rename(columns={'AUPR': 'Max_AUPR'})

        # Merge the max AUPR values back to the main DataFrame
        df = df.merge(max_aupr_per_alg, on=['Alg'])

        # Sort by 'Max_AUPR' and then by 'AUPR' within each algorithm group
        sorted_top_rows = df.sort_values(by=['Max_AUPR', 'AUPR'], ascending=[False, False])

        # Drop the Max_AUPR column as it was only used for sorting
        sorted_top_rows = sorted_top_rows.drop(columns='Max_AUPR', axis=1)

        # Prepare for further processing
        df = sorted_top_rows

        df['Group'] = df['Group'].replace('None', 'none')

        # Set the index
        df = df.set_index(['Alg', 'Group'])


    # # Save to CSV and LaTeX
    df.to_csv(f"{df_path}_table_top.csv" if all == False else f"{df_path}_table_all.csv")

    styled_df = df.style\
        .background_gradient(cmap="Oranges", subset=df.columns[0:]) \
        .format('{:.2f}', subset=df.columns[0:]) \
        .set_properties(**{'border': '1.3px solid black'})

    styled_df.to_latex(
        f"{df_path}_table_top.tex" if all == False else f"{df_path}_table_all.tex",
        clines="all;data",
        convert_css=True,
        position_float="centering",
        multicol_align="|c|",
        hrules=True,
    )
    display(styled_df)

table_generator("r_dicho")
table_generator("b_dicho")

# table_generator("r_dicho", all=True)
# table_generator("b_dicho", all=True)