In [ ]:
import os
import shutil

def get_directories(path):
    items = os.listdir(path)
    directories = [item for item in items if os.path.isdir(os.path.join(path, item))]
    return directories

current_directory = os.getcwd()

AllResults_path = f"{current_directory}/AllResults"
if not os.path.isdir(AllResults_path):
    os.makedirs(AllResults_path)

results_directories = get_directories(current_directory)

if "AllResults" in results_directories:
    results_directories.remove("AllResults")

for dir in results_directories:

    src = f"{current_directory}/{dir}/FinalResults"
    dst = f"{AllResults_path}/{dir}"

    if os.path.exists(src):  # cek dulu
        shutil.copytree(src, dst, dirs_exist_ok=True)
        print(f"Copied: {src}")
    else:
        print(f"Skipped (no FinalResults): {dir}")

Skipped (no FinalResults): .ipynb_checkpoints
Copied: C:\Users\iffah\Documents\Tugas\Data Mining\FundamentalPrediction\1_Classification\Conv_method/01_SKF_companySort_NoneGroup/FinalResults
Copied: C:\Users\iffah\Documents\Tugas\Data Mining\FundamentalPrediction\1_Classification\Conv_method/02_SKF_yearSort_NoneGroup/FinalResults
Copied: C:\Users\iffah\Documents\Tugas\Data Mining\FundamentalPrediction\1_Classification\Conv_method/03_SGKF_companySort_companyGroup/FinalResults
Copied: C:\Users\iffah\Documents\Tugas\Data Mining\FundamentalPrediction\1_Classification\Conv_method/04_SGKF_yearSort_companyGroup/FinalResults
Copied: C:\Users\iffah\Documents\Tugas\Data Mining\FundamentalPrediction\1_Classification\Conv_method/05_SGKF_companySort_yearGroup/FinalResults
Copied: C:\Users\iffah\Documents\Tugas\Data Mining\FundamentalPrediction\1_Classification\Conv_method/06_SGKF_yearSort_yearGroup/FinalResults

In [ ]:
finalResults_path = f"{AllResults_path}/FinalResults"
if not os.path.isdir(finalResults_path):
    os.makedirs(finalResults_path)

# Get a list of all directory names
finalResults_directories = get_directories(AllResults_path)

if "FinalResults" in finalResults_directories:
    finalResults_directories.remove("FinalResults")

print(finalResults_directories)

['01_SKF_companySort_NoneGroup', '02_SKF_yearSort_NoneGroup', '03_SGKF_companySort_companyGroup', '04_SGKF_yearSort_companyGroup', '05_SGKF_companySort_yearGroup', '06_SGKF_yearSort_yearGroup']

In [ ]:
preprocessing_methods = ["MinMax", "Standard"]
target_columns = ["r_dicho", "b_dicho"]


bar_plot_path = f"{finalResults_path}/bar_plot"
if not os.path.isdir(bar_plot_path):
    os.makedirs(bar_plot_path)

KBest_rankedFeatures_path = f"{finalResults_path}/KBest_rankedFeatures"
if not os.path.isdir(KBest_rankedFeatures_path):
    os.makedirs(KBest_rankedFeatures_path)

for dir in finalResults_directories:
    tmp_filePath = f"{AllResults_path}/{dir}"
    tmp_fileName = f"bar_plot.png"
    shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{bar_plot_path}/{dir}.png")

    tmp_filePath = f"{AllResults_path}/{dir}"
    tmp_fileName = f"final_KBest_rankedFeatures.csv"
    shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{KBest_rankedFeatures_path}/{dir}.csv")

    for target in target_columns:

        max_path = f"{finalResults_path}/max/{target}"
        if not os.path.isdir(max_path):
            os.makedirs(max_path)

        mean_path = f"{finalResults_path}/mean/{target}"
        if not os.path.isdir(mean_path):
            os.makedirs(mean_path)

        auc_roc_mean_path = f"{finalResults_path}/auc_roc_mean/{target}"
        if not os.path.isdir(auc_roc_mean_path):
            os.makedirs(auc_roc_mean_path)

        aupr_mean_path = f"{finalResults_path}/aupr_mean/{target}"
        if not os.path.isdir(aupr_mean_path):
            os.makedirs(aupr_mean_path)

        for pp_method in preprocessing_methods:

            tmp_filePath = f"{AllResults_path}/{dir}"
            tmp_fileName = f"{target}_max.csv"
            shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{max_path}/{dir}.csv")

            tmp_filePath = f"{AllResults_path}/{dir}"
            tmp_fileName = f"{target}_mean.csv"
            shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{mean_path}/{dir}.csv")

            tmp_filePath = f"{AllResults_path}/{dir}"
            tmp_fileName = f"{target}_{pp_method}_auc_roc_mean.png"
            shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{auc_roc_mean_path}/{dir}_{pp_method}.png")

            tmp_filePath = f"{AllResults_path}/{dir}"
            tmp_fileName = f"{target}_{pp_method}_aupr_mean.png"
            shutil.copy(f"{tmp_filePath}/{tmp_fileName}", f"{aupr_mean_path}/{dir}_{pp_method}.png")

In [ ]:
import pandas as pd

final_df = pd.DataFrame()

for dir in finalResults_directories:
    for target in target_columns:
        tmp_filePath = f"{AllResults_path}/{dir}"
        tmp_fileName = f"{target}_mean.csv"
        tmp_df = pd.read_csv(f"{tmp_filePath}/{tmp_fileName}")
        tmp_df.insert(0, "Target", f"{target}")
        tmp_df.insert(0, "Run_sample", f"{dir.split('_', 1)[1]}")
        final_df = pd.concat((final_df, tmp_df))

final_df = final_df.reset_index(drop=True)
final_df
# final_df.style.background_gradient(cmap="Reds", axis=False)

,Run_sample,Target,Scaling,Alg,Acc Cv,Acc Te,Sp,Se,MCC,F1,AUC-ROC,AUPR
0,SKF_companySort_NoneGroup,r_dicho,MinMax,DT,73.14 ± 0.79,71.48 ± 1.41,72.04 ± 4.46,71.13 ± 3.24,42.53 ± 2.97,75.27 ± 1.56,72.25 ± 2.27,84.33 ± 1.14
1,SKF_companySort_NoneGroup,r_dicho,MinMax,HGB,77.18 ± 1.86,76.59 ± 2.2,75.27 ± 2.59,77.42 ± 4.08,52.1 ± 3.71,80.13 ± 2.4,84.64 ± 1.79,90.54 ± 1.0
2,SKF_companySort_NoneGroup,r_dicho,MinMax,LR,71.26 ± 0.5,71.33 ± 0.65,89.08 ± 0.68,60.12 ± 1.2,48.8 ± 0.94,71.92 ± 0.86,81.03 ± 0.92,87.97 ± 0.44
3,SKF_companySort_NoneGroup,r_dicho,MinMax,RF,77.83 ± 1.87,76.58 ± 1.99,71.81 ± 3.39,79.59 ± 4.27,51.34 ± 3.43,80.56 ± 2.2,83.66 ± 1.52,89.48 ± 0.78
4,SKF_companySort_NoneGroup,r_dicho,MinMax,SVM,72.61 ± 0.35,72.38 ± 0.51,89.14 ± 0.83,61.79 ± 0.65,50.34 ± 1.04,73.2 ± 0.56,81.77 ± 1.4,88.55 ± 1.45
...,...,...,...,...,...,...,...,...,...,...,...,...
115,SGKF_yearSort_yearGroup,b_dicho,Standard,DT,58.67 ± 1.4,53.81 ± 2.09,40.68 ± 3.6,64.19 ± 3.84,4.94 ± 3.69,63.04 ± 2.67,52.52 ± 1.92,76.41 ± 1.26
116,SGKF_yearSort_yearGroup,b_dicho,Standard,HGB,58.03 ± 2.44,55.29 ± 2.74,41.89 ± 4.41,66.31 ± 6.21,8.57 ± 3.92,64.44 ± 4.46,55.33 ± 2.29,66.52 ± 1.66
117,SGKF_yearSort_yearGroup,b_dicho,Standard,LR,45.34 ± 1.96,42.38 ± 2.3,79.44 ± 4.27,23.5 ± 5.61,4.06 ± 2.61,30.42 ± 7.32,58.91 ± 1.85,69.8 ± 0.87
118,SGKF_yearSort_yearGroup,b_dicho,Standard,RF,62.01 ± 2.11,58.25 ± 2.38,33.63 ± 2.9,76.03 ± 4.67,11.12 ± 4.1,69.15 ± 2.7,56.3 ± 2.23,67.44 ± 1.3
119,SGKF_yearSort_yearGroup,b_dicho,Standard,SVM,41.73 ± 1.7,39.64 ± 1.46,83.36 ± 4.5,16.66 ± 4.19,-0.49 ± 2.42,21.41 ± 5.53,55.28 ± 2.57,67.75 ± 1.52

In [ ]:
# Function to extract mean and std components and convert to numeric types
def extract_and_convert(value):
    mean, std = map(float, value.split(' ± '))
    return mean, std

metrics = [
    'Acc Cv', 'Acc Te', 'Sp', 'Se',
    'MCC', 'F1', 'AUC-ROC', 'AUPR'
]

new_final_df = pd.DataFrame()
for i, col in enumerate(final_df.columns):
    if col not in metrics:
        new_final_df[col] = final_df[col].values.copy()

    else:
        new_final_df[[f"{col}_mean", f"{col}_std"]] = final_df[col].apply(extract_and_convert).apply(pd.Series)

new_final_df

,Run_sample,Target,Scaling,Alg,Acc Cv_mean,Acc Cv_std,Acc Te_mean,Acc Te_std,Sp_mean,Sp_std,Se_mean,Se_std,MCC_mean,MCC_std,F1_mean,F1_std,AUC-ROC_mean,AUC-ROC_std,AUPR_mean,AUPR_std
0,SKF_companySort_NoneGroup,r_dicho,MinMax,DT,73.14,0.79,71.48,1.41,72.04,4.46,71.13,3.24,42.53,2.97,75.27,1.56,72.25,2.27,84.33,1.14
1,SKF_companySort_NoneGroup,r_dicho,MinMax,HGB,77.18,1.86,76.59,2.20,75.27,2.59,77.42,4.08,52.10,3.71,80.13,2.40,84.64,1.79,90.54,1.00
2,SKF_companySort_NoneGroup,r_dicho,MinMax,LR,71.26,0.50,71.33,0.65,89.08,0.68,60.12,1.20,48.80,0.94,71.92,0.86,81.03,0.92,87.97,0.44
3,SKF_companySort_NoneGroup,r_dicho,MinMax,RF,77.83,1.87,76.58,1.99,71.81,3.39,79.59,4.27,51.34,3.43,80.56,2.20,83.66,1.52,89.48,0.78
4,SKF_companySort_NoneGroup,r_dicho,MinMax,SVM,72.61,0.35,72.38,0.51,89.14,0.83,61.79,0.65,50.34,1.04,73.20,0.56,81.77,1.40,88.55,1.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,SGKF_yearSort_yearGroup,b_dicho,Standard,DT,58.67,1.40,53.81,2.09,40.68,3.60,64.19,3.84,4.94,3.69,63.04,2.67,52.52,1.92,76.41,1.26
116,SGKF_yearSort_yearGroup,b_dicho,Standard,HGB,58.03,2.44,55.29,2.74,41.89,4.41,66.31,6.21,8.57,3.92,64.44,4.46,55.33,2.29,66.52,1.66
117,SGKF_yearSort_yearGroup,b_dicho,Standard,LR,45.34,1.96,42.38,2.30,79.44,4.27,23.50,5.61,4.06,2.61,30.42,7.32,58.91,1.85,69.80,0.87
118,SGKF_yearSort_yearGroup,b_dicho,Standard,RF,62.01,2.11,58.25,2.38,33.63,2.90,76.03,4.67,11.12,4.10,69.15,2.70,56.30,2.23,67.44,1.30
119,SGKF_yearSort_yearGroup,b_dicho,Standard,SVM,41.73,1.70,39.64,1.46,83.36,4.50,16.66,4.19,-0.49,2.42,21.41,5.53,55.28,2.57,67.75,1.52

In [ ]:
new_final_df = new_final_df.sort_values(by="AUPR_mean", ascending=False, ignore_index=True)
new_final_df.to_csv("final_df.csv", index=False)
new_final_df

,Run_sample,Target,Scaling,Alg,Acc Cv_mean,Acc Cv_std,Acc Te_mean,Acc Te_std,Sp_mean,Sp_std,Se_mean,Se_std,MCC_mean,MCC_std,F1_mean,F1_std,AUC-ROC_mean,AUC-ROC_std,AUPR_mean,AUPR_std
0,SKF_yearSort_NoneGroup,r_dicho,Standard,HGB,77.00,1.87,76.98,1.87,74.95,2.66,78.26,4.03,52.72,2.96,80.57,2.14,85.03,1.51,90.78,0.82
1,SKF_yearSort_NoneGroup,r_dicho,MinMax,HGB,77.00,1.87,76.97,1.88,74.92,2.62,78.26,4.03,52.69,2.97,80.56,2.15,85.02,1.51,90.76,0.81
2,SGKF_yearSort_companyGroup,r_dicho,MinMax,HGB,76.88,1.74,76.75,1.98,74.74,2.71,78.09,3.78,52.25,3.38,80.37,2.16,84.90,1.59,90.74,0.85
3,SGKF_companySort_companyGroup,r_dicho,MinMax,HGB,76.88,1.74,76.73,1.99,74.71,2.73,78.08,3.79,52.23,3.39,80.36,2.16,84.89,1.60,90.73,0.85
4,SGKF_yearSort_companyGroup,r_dicho,Standard,HGB,76.88,1.74,76.74,1.98,74.70,2.74,78.10,3.81,52.23,3.36,80.37,2.16,84.89,1.59,90.73,0.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,SGKF_companySort_yearGroup,b_dicho,Standard,RF,61.92,2.15,58.13,2.20,33.35,2.95,75.94,4.57,10.83,3.87,69.06,2.58,56.15,2.07,67.31,1.29
116,SGKF_yearSort_yearGroup,b_dicho,Standard,HGB,58.03,2.44,55.29,2.74,41.89,4.41,66.31,6.21,8.57,3.92,64.44,4.46,55.33,2.29,66.52,1.66
117,SGKF_companySort_yearGroup,b_dicho,MinMax,HGB,58.03,2.43,55.31,2.72,41.92,4.41,66.33,6.19,8.62,3.84,64.46,4.44,55.33,2.28,66.51,1.64
118,SGKF_companySort_yearGroup,b_dicho,Standard,HGB,58.02,2.44,55.31,2.72,41.88,4.41,66.35,6.21,8.59,3.88,64.47,4.45,55.33,2.28,66.51,1.66
119,SGKF_yearSort_yearGroup,b_dicho,MinMax,HGB,58.02,2.44,55.30,2.71,41.89,4.40,66.34,6.19,8.59,3.82,64.46,4.44,55.32,2.27,66.49,1.65

In [ ]:
for target in target_columns:
    tmp_df = new_final_df.groupby("Target").get_group(target).reset_index(drop=True)
    tmp_df.drop(columns="Target", inplace=True)
    tmp_df.to_csv(f"{target}_df.csv", index=False)

In [ ]:
# Load the DataFrame
r_dicho_df = pd.read_csv("r_dicho_df.csv")
r_dicho_df = r_dicho_df[r_dicho_df["Alg"] != "DT"]
r_dicho_df

,Run_sample,Scaling,Alg,Acc Cv_mean,Acc Cv_std,Acc Te_mean,Acc Te_std,Sp_mean,Sp_std,Se_mean,Se_std,MCC_mean,MCC_std,F1_mean,F1_std,AUC-ROC_mean,AUC-ROC_std,AUPR_mean,AUPR_std
0,SKF_yearSort_NoneGroup,Standard,HGB,77.00,1.87,76.98,1.87,74.95,2.66,78.26,4.03,52.72,2.96,80.57,2.14,85.03,1.51,90.78,0.82
1,SKF_yearSort_NoneGroup,MinMax,HGB,77.00,1.87,76.97,1.88,74.92,2.62,78.26,4.03,52.69,2.97,80.56,2.15,85.02,1.51,90.76,0.81
2,SGKF_yearSort_companyGroup,MinMax,HGB,76.88,1.74,76.75,1.98,74.74,2.71,78.09,3.78,52.25,3.38,80.37,2.16,84.90,1.59,90.74,0.85
3,SGKF_companySort_companyGroup,MinMax,HGB,76.88,1.74,76.73,1.99,74.71,2.73,78.08,3.79,52.23,3.39,80.36,2.16,84.89,1.60,90.73,0.85
4,SGKF_yearSort_companyGroup,Standard,HGB,76.88,1.74,76.74,1.98,74.70,2.74,78.10,3.81,52.23,3.36,80.37,2.16,84.89,1.59,90.73,0.86
5,SGKF_companySort_companyGroup,Standard,HGB,76.88,1.73,76.76,1.99,74.75,2.71,78.09,3.80,52.27,3.39,80.38,2.17,84.90,1.59,90.73,0.85
6,SKF_companySort_NoneGroup,Standard,HGB,77.18,1.86,76.59,2.20,75.29,2.59,77.41,4.07,52.10,3.71,80.13,2.40,84.65,1.78,90.55,1.00
7,SKF_companySort_NoneGroup,MinMax,HGB,77.18,1.86,76.59,2.20,75.27,2.59,77.42,4.08,52.10,3.71,80.13,2.40,84.64,1.79,90.54,1.00
8,SGKF_yearSort_companyGroup,MinMax,RF,77.62,1.67,76.63,1.86,71.40,2.86,80.02,3.82,51.39,3.27,80.67,2.01,84.06,1.41,89.81,0.75
9,SGKF_yearSort_companyGroup,Standard,RF,77.62,1.68,76.62,1.91,71.35,2.85,80.04,3.85,51.37,3.36,80.67,2.04,84.06,1.43,89.80,0.77
10,SGKF_companySort_companyGroup,Standard,RF,77.58,1.68,76.61,1.94,71.53,3.05,79.90,4.05,51.40,3.34,80.63,2.13,84.02,1.46,89.77,0.79
11,SGKF_companySort_companyGroup,MinMax,RF,77.57,1.68,76.62,1.95,71.50,2.96,79.95,4.11,51.42,3.34,80.64,2.15,84.01,1.45,89.74,0.76
12,SKF_yearSort_NoneGroup,Standard,RF,77.76,1.87,76.98,1.86,71.94,2.77,80.16,4.04,52.08,3.10,80.95,2.08,84.06,1.28,89.70,0.63
13,SKF_yearSort_NoneGroup,MinMax,RF,77.77,1.86,76.96,1.83,72.00,2.85,80.08,4.01,52.07,3.04,80.92,2.06,84.03,1.26,89.68,0.65
14,SKF_companySort_NoneGroup,Standard,RF,77.82,1.86,76.59,1.99,71.80,3.40,79.62,4.22,51.38,3.46,80.57,2.18,83.68,1.53,89.49,0.78
15,SKF_companySort_NoneGroup,MinMax,RF,77.83,1.87,76.58,1.99,71.81,3.39,79.59,4.27,51.34,3.43,80.56,2.20,83.66,1.52,89.48,0.78
16,SGKF_yearSort_companyGroup,MinMax,SVM,72.59,0.33,72.76,0.54,89.39,0.74,62.32,0.72,50.97,0.99,73.67,0.58,81.99,1.37,88.81,1.41
17,SGKF_companySort_companyGroup,MinMax,SVM,72.59,0.33,72.77,0.54,89.39,0.73,62.32,0.72,50.98,0.99,73.67,0.58,81.99,1.36,88.80,1.42
18,SKF_yearSort_NoneGroup,MinMax,SVM,72.48,0.32,72.53,0.40,89.25,0.82,61.98,0.53,50.62,0.88,73.41,0.42,81.74,1.21,88.60,1.23
19,SKF_companySort_NoneGroup,MinMax,SVM,72.61,0.35,72.38,0.51,89.14,0.83,61.79,0.65,50.34,1.04,73.20,0.56,81.77,1.40,88.55,1.45
20,SGKF_yearSort_companyGroup,Standard,LR,72.51,0.86,72.79,0.98,88.21,1.04,63.06,1.92,50.46,1.35,73.86,1.28,81.91,1.12,88.35,0.59
21,SGKF_companySort_companyGroup,Standard,LR,72.52,0.85,72.79,0.98,88.21,1.03,63.06,1.91,50.46,1.34,73.86,1.27,81.90,1.12,88.34,0.59
22,SGKF_companySort_companyGroup,MinMax,LR,71.23,0.50,71.57,0.70,88.73,0.72,60.75,1.20,48.89,1.05,72.29,0.88,81.24,0.95,88.16,0.50
23,SGKF_yearSort_companyGroup,MinMax,LR,71.23,0.50,71.57,0.70,88.73,0.72,60.75,1.21,48.89,1.05,72.29,0.88,81.24,0.95,88.16,0.50
24,SKF_yearSort_NoneGroup,Standard,LR,72.65,0.93,72.81,1.12,87.80,1.25,63.34,2.20,50.35,1.57,73.98,1.45,81.83,1.12,88.14,0.59
25,SGKF_yearSort_companyGroup,Standard,SVM,72.87,0.69,72.88,0.90,88.63,0.90,62.95,1.38,50.76,1.48,73.91,1.05,81.52,1.48,88.06,1.42
26,SGKF_companySort_companyGroup,Standard,SVM,72.87,0.68,72.88,0.89,88.62,0.89,62.96,1.37,50.76,1.46,73.92,1.04,81.52,1.48,88.05,1.43
27,SKF_yearSort_NoneGroup,MinMax,LR,71.29,0.51,71.56,0.67,89.11,0.72,60.49,1.19,49.15,1.00,72.21,0.86,80.99,0.91,88.01,0.43
28,SKF_companySort_NoneGroup,Standard,LR,72.69,0.91,72.47,1.11,87.81,1.26,62.78,2.04,49.85,1.69,73.58,1.39,81.72,1.12,87.98,0.60
29,SKF_companySort_NoneGroup,MinMax,LR,71.26,0.50,71.33,0.65,89.08,0.68,60.12,1.20,48.80,0.94,71.92,0.86,81.03,0.92,87.97,0.44
30,SKF_yearSort_NoneGroup,Standard,SVM,72.72,0.69,72.74,0.87,88.17,0.89,62.99,1.39,50.40,1.44,73.85,1.03,81.49,1.43,87.95,1.34
31,SKF_companySort_NoneGroup,Standard,SVM,72.90,0.76,72.44,0.96,88.00,0.87,62.61,1.50,49.88,1.58,73.50,1.12,81.52,1.54,87.83,1.42
34,SGKF_yearSort_yearGroup,MinMax,LR,62.81,0.89,64.47,3.49,83.00,6.96,46.49,5.57,30.58,9.13,52.04,5.53,76.92,4.78,84.44,5.14
36,SGKF_companySort_yearGroup,MinMax,LR,62.81,0.89,64.48,3.49,83.00,6.96,46.49,5.58,30.58,9.14,52.05,5.53,76.92,4.77,84.43,5.14
42,SGKF_companySort_yearGroup,Standard,LR,64.79,1.34,65.56,3.37,80.72,6.02,49.64,5.01,31.49,7.48,55.48,4.66,76.55,4.22,83.95,4.12
43,SGKF_yearSort_yearGroup,Standard,LR,64.79,1.34,65.56,3.37,80.72,6.02,49.64,5.01,31.48,7.46,55.47,4.65,76.55,4.22,83.95,4.12
44,SGKF_companySort_yearGroup,Standard,SVM,63.24,1.49,62.67,3.89,82.54,6.43,44.94,4.69,28.95,6.88,51.22,5.02,75.10,4.81,82.85,3.83
45,SGKF_yearSort_yearGroup,Standard,SVM,63.25,1.48,62.69,3.89,82.54,6.41,44.98,4.68,28.96,6.89,51.26,5.02,75.09,4.81,82.84,3.83
46,SGKF_companySort_yearGroup,MinMax,SVM,61.47,1.37,59.67,4.64,84.57,6.11,38.47,4.53,24.49,7.55,44.35,5.12,73.76,5.38,81.77,4.53
47,SGKF_yearSort_yearGroup,MinMax,SVM,61.47,1.37,59.66,4.62,84.58,6.10,38.46,4.50,24.49,7.52,44.35,5.10,73.73,5.36,81.74,4.51
48,SGKF_yearSort_yearGroup,MinMax,RF,69.86,2.82,67.50,3.52,54.76,9.35,73.14,5.21,29.83,8.62,70.45,4.33,72.33,4.99,81.14,3.77
49,SGKF_yearSort_yearGroup,Standard,RF,69.86,2.81,67.49,3.54,54.63,9.31,73.14,5.17,29.69,8.63,70.45,4.34,72.30,4.94,81.10,3.73
50,SGKF_companySort_yearGroup,Standard,RF,69.88,2.80,67.15,3.58,54.10,9.42,73.18,5.24,29.21,8.81,70.15,4.34,72.09,5.09,80.94,3.68
51,SGKF_companySort_yearGroup,MinMax,RF,69.87,2.79,67.14,3.60,54.35,9.57,73.01,5.26,29.25,8.96,70.07,4.37,72.13,5.05,80.92,3.69
52,SGKF_yearSort_yearGroup,MinMax,HGB,67.94,2.06,64.80,4.86,58.15,8.63,68.36,6.32,27.83,7.33,67.07,5.85,71.15,4.06,79.84,3.28
53,SGKF_companySort_yearGroup,MinMax,HGB,67.93,2.06,64.80,4.85,58.12,8.61,68.39,6.32,27.83,7.31,67.08,5.85,71.13,4.06,79.84,3.28
54,SGKF_companySort_yearGroup,Standard,HGB,67.94,2.07,64.80,4.83,58.20,8.58,68.36,6.26,27.87,7.28,67.07,5.81,71.17,4.04,79.83,3.27
55,SGKF_yearSort_yearGroup,Standard,HGB,67.94,2.06,64.81,4.83,58.17,8.58,68.40,6.27,27.90,7.30,67.08,5.81,71.16,4.04,79.82,3.28

In [ ]:
def table_generator(df_path, all=False):

    df = pd.read_csv(f"{df_path}_df.csv")

    # Rename and clean columns
    for col in df.columns:
        if "Acc Te" in col:
            df = df.rename(columns={col: col.replace("Acc Te_mean", "Acc")})
        if "_mean" in col:
            df = df.rename(columns={col: col.replace("_mean", "")})
        if "_std" in col:
            df = df.drop(columns=col)

    df = df[df["Alg"] != "DT"]  # Remove the 'DT' algorithm

    df = df[['Run_sample', 'Alg', 'Scaling', 'Acc', 'MCC', 'AUC-ROC', 'AUPR']]

    # Split 'Run_sample' into separate columns
    Run_sample = ['Fold', 'Sort', 'Group']
    df[Run_sample] = df['Run_sample'].str.split('_', expand=True)
    df = df.drop(columns=["Run_sample"])
    df['Sort'] = df['Sort'].str.replace('Sort', '')
    df['Group'] = df['Group'].str.replace('Group', '')

    df = df.sort_values(by=['AUPR', 'AUC-ROC'], ascending=[False, False], ignore_index = True)

    if all == True:
        df = df[['Alg', 'Fold', 'Group', 'Sort', 'Scaling', 'Acc', 'MCC', 'AUC-ROC', 'AUPR']]

        # Set the index
        df = df.set_index(['Alg', 'Fold', 'Group', 'Sort', 'Scaling'])

    else:

        # df = df[df['Sort'] != "company"]  # Filter out 'company' sort

        df = df[['Alg', 'Group', 'Acc', 'MCC', 'AUC-ROC', 'AUPR']]

        df = df.drop_duplicates(subset=['Alg','Group'], keep='first')

        # Calculate the maximum AUPR value for each algorithm group
        max_aupr_per_alg = df.groupby(by=['Alg'])['AUPR'].max().reset_index()
        max_aupr_per_alg = max_aupr_per_alg.rename(columns={'AUPR': 'Max_AUPR'})

        # Merge the max AUPR values back to the main DataFrame
        df = df.merge(max_aupr_per_alg, on=['Alg'])

        # Sort by 'Max_AUPR' and then by 'AUPR' within each algorithm group
        sorted_top_rows = df.sort_values(by=['Max_AUPR', 'AUPR'], ascending=[False, False])

        # Drop the Max_AUPR column as it was only used for sorting
        sorted_top_rows = sorted_top_rows.drop(columns='Max_AUPR', axis=1)

        # Prepare for further processing
        df = sorted_top_rows

        df['Group'] = df['Group'].replace('None', 'none')

        # Set the index
        df = df.set_index(['Alg', 'Group'])


    # # Save to CSV and LaTeX
    df.to_csv(f"{df_path}_table_top.csv" if all == False else f"{df_path}_table_all.csv")

    styled_df = df.style\
        .background_gradient(cmap="Oranges", subset=df.columns[0:]) \
        .format('{:.2f}', subset=df.columns[0:]) \
        .set_properties(**{'border': '1.3px solid black'})

    styled_df.to_latex(
        f"{df_path}_table_top.tex" if all == False else f"{df_path}_table_all.tex",
        clines="all;data",
        convert_css=True,
        position_float="centering",
        multicol_align="|c|",
        hrules=True,
    )
    display(styled_df)

table_generator("r_dicho")
table_generator("b_dicho")

# table_generator("r_dicho", all=True)
# table_generator("b_dicho", all=True)